### ISSUE TITLE
HTTP2 push

### ISSUE THREAD

**Issue by martinvenus** [webrouse/n-asset-macro#4]
Hi,

is there please any possibility to automatically set the Link header for HTTP2 push?

Thank you!

**Comment by webrouse** [comment]
This is not possible at the moment, but it is an interesting idea.

**Comment by webrouse** [comment]
In the new version `v2.0.0` was introduced new `ManifestService` to read manifest data from PHP code.

See: https://github.com/webrouse/n-asset-macro#manifestservice

You can now use it for set **HTTP2 push** headers:
- add new callback to event `Nette\Application\Application::$onResponse[]` (in config file or custom extension)
- load/inject `Webrouse\AssetMacro\ManifestService` from DI container
- use assets from `$manifestService->getManifest()->getAll($filter)` to generate desired headers
